# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "tranphuquy19/centos7"
    config.vm.box_version = "1.0.0"
    config.vm.network "private_network", ip: "172.16.10.105"
    config.vm.hostname = "worker3.dora"
  
    config.vm.provider "virtualbox" do |vb|
        vb.name = "worker4.dora"
        vb.cpus = 2
        vb.memory = "2048"
    end
  
    config.vm.provision "shell", inline: <<-SHELL
echo "11231123" | passwd --stdin root
sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
systemctl reload sshd
SHELL

end