# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "tranphuquy19/centos7-gitlab-server"
  config.vm.network "private_network", ip: "10.10.10.11"
  config.vm.hostname = "gitlab.dora"

  config.vm.provider "virtualbox" do |vb|
      vb.name = "gitlab.dora"
      vb.cpus = 3
      vb.memory = "3072"
  end

  config.vm.provision "shell", inline: <<-SHELL
echo "11231123" | passwd --stdin root
sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
systemctl reload sshd
SHELL

end