# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.box = "tranphuquy19/centos7-k8s"
    config.vm.box_version = "1.0.0"
    config.vm.network "private_network", ip: "172.16.10.103"
    config.vm.hostname = "worker3.dora"
  
    config.vm.provider "virtualbox" do |vb|
        vb.name = "worker3.dora"
        vb.cpus = 1
        vb.memory = "2048"
    end
  
    config.vm.provision "shell", inline: <<-SHELL
echo "11231123" | passwd --stdin root
sed -i 's/^PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
systemctl reload sshd
cat >>/etc/hosts<<EOF
172.16.10.100 master.dora
172.16.10.101 worker1.dora
172.16.10.102 worker2.dora
EOF
SHELL

end