apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nestjs
  name: nestjs-test
spec:
  containers:
  - name: c1
    image: tranphuquy19/nestjs-jenkins:latest
    resources:
      limits:
        memory: "150M"
        cpu: "100m"
    ports:
      - containerPort: 3000