apiVersion: v1
kind: Service
metadata:
  name: nest-app
spec:
  selector:
    app: nestjs
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nestjs
  name: nestjs-test1
spec:
  containers:
    - name: c1
      image: tranphuquy19/nestjs-jenkins:latest
      resources:
        limits:
          memory: "500M"
          cpu: "300m"
      ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: nestjs
  name: nestjs-test2
spec:
  containers:
    - name: c1
      image: tranphuquy19/nestjs-jenkins:latest
      resources:
        limits:
          memory: "500M"
          cpu: "300m"
      ports:
        - containerPort: 3000
