apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server-app
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30475
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: server-app
  name: nginx-pod-1
spec:
  containers:
    - name: nginx-con
      image: nginx
      resources:
        limits:
          memory: "100M"
          cpu: "100m"
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: server-app
  name: nginx-pod-2
spec:
  containers:
    - name: nginx-con
      image: nginx
      resources:
        limits:
          memory: "100M"
          cpu: "100m"
      ports:
        - containerPort: 80
