apiVersion: v1
kind: Service
metadata:
  name: server-service
spec:
  selector:
    app: server-app
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: server-app
  name: nginx-pod
spec:
  containers:
    - name: nginx-app
      image: nginx
      resources:
        limits:
          memory: "100M"
          cpu: "100m"
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: server-app
  name: httpd-app
spec:
  containers:
    - name: httpd-app
      image: httpd
      resources:
        limits:
          memory: "100M"
          cpu: "100M"
      ports:
        - containerPort: 80
